### ISSUE TITLE
curl not a required dependency

### ISSUE THREAD

**Issue by jcorb** [conda-forge/herbie-data-feedstock#2]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi - herbie is an awesome package 🙌 

just FYI installing via `conda-forge` doesn't seem to install `curl` (which it should right?).

This is what I get for the output of `mamba repoquery depends herbie-data --channel conda-forge` (so no `curl` dependency)
```
Executing the query herbie-data

conda-forge/noarch                                  13.4MB @   3.3MB/s  4.6s
conda-forge/osx-64                                  29.7MB @   2.8MB/s 11.9s


 Name        Version  Build                  Channel           
────────────────────────────────────────────────────────────────
 herbie-data 2023.3.0 pyhd8ed1ab_0           conda-forge/noarch
 cfgrib      0.9.10.4 pyhd8ed1ab_0           conda-forge/noarch
 metpy       0.10.0   py27_1001              conda-forge/osx-64
 numpy       1.10.4   py27_blas_openblas_200 conda-forge/osx-64
 pandas      0.17.0   np110py27_0            conda-forge/osx-64
 pygrib      2.0.1    py27_1                 conda-forge/osx-64
 python      3.9.16   h709bd14_0_cpython     conda-forge/osx-64
 toml        0.10.0   py_0                   conda-forge/noarch
 xarray      0.10.0   py27_0                 conda-forge/osx-64
```

Not super familiar with conda packaging, but I imagine it just needs to be added to the `meta.yaml`? Happy to do a PR if you like.

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by blaylockbk** [comment]
Thanks for bringing this to my attention. Yes, I thought curl was installed, but it doesn't look like it is. Seems like it should be added in the `meta.yml` as you said.

https://github.com/conda-forge/herbie-data-feedstock/blob/65911186aae2a8f3ea7cdcf163f62c9f8738363e/recipe/meta.yaml#L26-L34

**Comment by blaylockbk** [comment]
I updated the feedstock and it now shows curl as a dependency.

```
conda search --channel conda-forge --info herbie-data
```

```
herbie-data 2023.3.0 pyhd8ed1ab_1
---------------------------------
file name   : herbie-data-2023.3.0-pyhd8ed1ab_1.conda
name        : herbie-data
version     : 2023.3.0
build       : pyhd8ed1ab_1
build number: 1
size        : 50 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/herbie-data-2023.3.0-pyhd8ed1ab_1.conda
md5         : 3fa78f5caad255844847fb2980bf7728
timestamp   : 2023-07-27 16:32:50 UTC
dependencies: 
  - cfgrib >=0.9.10.1
  - curl
  - metpy
  - numpy
  - pandas
  - pygrib
  - python >=3.8
  - toml
  - xarray
```

I tested with

```
conda create -n test-herbie --channel conda-forge herbie-data
```
and it looks like it worked as expected.

Thanks for raising this issue, @jcorb
